<?php

namespace App\Controller;

use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;

use App\Entity\Rezume;
use App\Form\RezumeForm;

use Symfony\Component\HttpFoundation\File\Exception\FileException;
use Symfony\Component\HttpFoundation\Request;


class RezumeController extends Controller
{
    /**
     * @Route("/rezume", name="rezume")
     */
    public function index()
    {
        // replace this line with your own code!
        return $this->render('@Maker/demoPage.html.twig', [ 'path' => str_replace($this->getParameter('kernel.project_dir').'/', '', __FILE__) ]);
    }

    public function show($id)
    {
        $rezume = $this->getDoctrine()
            ->getRepository(Rezume::class)
            ->find($id);

        dump($rezume);

        return $this->render('rezume.html.twig', ['rezume' => $rezume]);
    }


    /**
     * @return string
     */
    private function generateUniqueFileName()
    {
        // md5() reduces the similarity of the file names generated by
        // uniqid(), which is based on timestamps
        return md5(uniqid());
    }    

}
